#!/usr/bin/env bash
# Usage: init-trip.sh <trip-name> [output-dir]
# Creates the full trip output folder with all deliverable files pre-scaffolded.

set -euo pipefail

TRIP_NAME="${1:?Usage: init-trip.sh <trip-name> [output-dir]}"
OUTPUT_DIR="${2:-$(pwd)/trips}"
TRIP_DIR="${OUTPUT_DIR}/${TRIP_NAME}"

if [ -d "$TRIP_DIR" ]; then
  echo "Error: Trip folder already exists: $TRIP_DIR"
  exit 1
fi

mkdir -p "$TRIP_DIR"

# Create all deliverable files with headers
cat > "$TRIP_DIR/00-overview.md" << 'HEADER'
# Trip Overview

> Auto-generated by /travel-agent

## Trip Details
- **Destination:**
- **Dates:**
- **Duration:**
- **Travelers:**
- **Budget Tier:**
- **Travel Style:**

## Quick Links
- [Itinerary](./01-itinerary.md)
- [Country Guide](./02-country-guide.md)
- [Accommodations](./03-accommodations.md)
- [Transport](./04-transport.md)
- [Food & Dining](./05-food-guide.md)
- [Hidden Gems](./06-hidden-gems.md)
- [Activities & Experiences](./07-activities.md)
- [Budget & Costs](./08-budget.md)
- [Checklists](./09-checklists.md)
- [Bookings & Links](./10-bookings.md)
- [Plan B & Contingencies](./11-plan-b.md)
- [Daily Pocket Guide](./12-pocket-guide.md)
- [Maps & Routes](./13-maps-and-routes.md)
- [Photo Guide](./14-photo-guide.md)
- [Step-by-Step Guides](./15-step-by-step-guides.md)
- [Booking Timeline](./16-booking-timeline.md)
- [Communication Cards](./17-communication-cards.md)
- [Companion Briefing](./18-companion-briefing.md)
- [Post-Trip Guide](./19-post-trip.md)
HEADER

touch "$TRIP_DIR/01-itinerary.md"
touch "$TRIP_DIR/02-country-guide.md"
touch "$TRIP_DIR/03-accommodations.md"
touch "$TRIP_DIR/04-transport.md"
touch "$TRIP_DIR/05-food-guide.md"
touch "$TRIP_DIR/06-hidden-gems.md"
touch "$TRIP_DIR/07-activities.md"
touch "$TRIP_DIR/08-budget.md"
touch "$TRIP_DIR/09-checklists.md"
touch "$TRIP_DIR/10-bookings.md"
touch "$TRIP_DIR/11-plan-b.md"
touch "$TRIP_DIR/12-pocket-guide.md"
touch "$TRIP_DIR/13-maps-and-routes.md"
touch "$TRIP_DIR/14-photo-guide.md"
touch "$TRIP_DIR/15-step-by-step-guides.md"
touch "$TRIP_DIR/16-booking-timeline.md"
touch "$TRIP_DIR/17-communication-cards.md"
touch "$TRIP_DIR/18-companion-briefing.md"
touch "$TRIP_DIR/19-post-trip.md"

# Generate index file
cat > "$TRIP_DIR/_index.md" << 'INDEX'
# Trip Files Index

> Auto-generated. This file lists all deliverables and their status.

| File | Status | Last Updated |
|---|---|---|
INDEX

for f in "$TRIP_DIR"/*.md; do
  filename=$(basename "$f")
  if [ "$filename" != "_index.md" ]; then
    echo "| [$filename](./$filename) | Draft | $(date +%Y-%m-%d) |" >> "$TRIP_DIR/_index.md"
  fi
done

echo "Trip folder created: $TRIP_DIR"
echo "Files: $(ls "$TRIP_DIR" | wc -l | tr -d ' ') deliverables ready"
